<?php
require_once __DIR__.'/../includes/account.php';
$uid=account_require_login(); $accountPage=$accountPage ?? 'profile';

if ($_SERVER['REQUEST_METHOD']==='POST') {
 account_check_csrf(); $action=$_POST['action']??'';
 if ($action==='profile') {
  $name=trim($_POST['name']??''); $email=trim($_POST['email']??''); $phone=trim($_POST['phone']??''); $birthday=$_POST['birthday']?:null; $gender=$_POST['gender']??'';
  if ($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)) account_redirect('', 'Please enter a valid name and email.');
  $s=$conn->prepare('UPDATE users SET name=?,email=?,phone=?,birthday=?,gender=? WHERE id=?'); $s->bind_param('sssssi',$name,$email,$phone,$birthday,$gender,$uid); $s->execute();
  $_SESSION['user_name']=$name; $_SESSION['email']=$email; account_redirect('', 'Profile updated.');
 }
 if ($action==='address_save') {
  foreach(['full_name','phone','address_line','district','province','postal_code','country'] as $f) if(trim($_POST[$f]??'')==='') account_redirect('addresses/','Please complete every required address field.');
  $id=(int)($_POST['id']??0); $label=trim($_POST['label']??'Home'); $full=trim($_POST['full_name']);$phone=trim($_POST['phone']);$line=trim($_POST['address_line']);$sub=trim($_POST['subdistrict']??'');$district=trim($_POST['district']);$province=trim($_POST['province']);$postal=trim($_POST['postal_code']);$country=trim($_POST['country']);$def=isset($_POST['is_default'])?1:0;
  if($def){$s=$conn->prepare('UPDATE addresses SET is_default=0 WHERE user_id=?');$s->bind_param('i',$uid);$s->execute();}
  if($id){$s=$conn->prepare('UPDATE addresses SET label=?,full_name=?,phone=?,address_line=?,subdistrict=?,district=?,province=?,postal_code=?,country=?,is_default=? WHERE id=? AND user_id=?');$s->bind_param('sssssssssiii',$label,$full,$phone,$line,$sub,$district,$province,$postal,$country,$def,$id,$uid);} 
  else {$count=$conn->query('SELECT COUNT(*) c FROM addresses WHERE user_id='.(int)$uid)->fetch_assoc()['c'];if(!$count)$def=1;$s=$conn->prepare('INSERT INTO addresses(user_id,label,full_name,phone,address_line,subdistrict,district,province,postal_code,country,is_default) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->bind_param('isssssssssi',$uid,$label,$full,$phone,$line,$sub,$district,$province,$postal,$country,$def);}
  $s->execute(); account_redirect('addresses/','Address saved.');
 }
 if ($action==='address_delete'||$action==='address_default') { $id=(int)($_POST['id']??0); if($action==='address_delete'){$conn->begin_transaction();$s=$conn->prepare('SELECT is_default FROM addresses WHERE id=? AND user_id=? FOR UPDATE');$s->bind_param('ii',$id,$uid);$s->execute();$address=$s->get_result()->fetch_assoc();if(!$address){$conn->rollback();account_redirect('addresses/','Address not found.');}$s=$conn->prepare('DELETE FROM addresses WHERE id=? AND user_id=?');$s->bind_param('ii',$id,$uid);$s->execute();if((int)$address['is_default']===1){$s=$conn->prepare('UPDATE addresses SET is_default=1 WHERE user_id=? ORDER BY id DESC LIMIT 1');$s->bind_param('i',$uid);$s->execute();}$conn->commit();account_redirect('addresses/','Address removed.');}else{$conn->begin_transaction();$s=$conn->prepare('UPDATE addresses SET is_default=0 WHERE user_id=?');$s->bind_param('i',$uid);$s->execute();$s=$conn->prepare('UPDATE addresses SET is_default=1 WHERE id=? AND user_id=?');$s->bind_param('ii',$id,$uid);$s->execute();$conn->commit();account_redirect('addresses/','Default address updated.');} }
 if ($action==='payment_save') {
  $provider=strtolower(trim($_POST['provider']??''));$token=trim($_POST['payment_method_id']??'');$brand=trim($_POST['brand']??'');$last4=trim($_POST['last4']??'');$month=(int)($_POST['expiry_month']??0);$year=(int)($_POST['expiry_year']??0);
  if(!in_array($provider,['stripe','omise','opn','2c2p'],true)||!preg_match('/^[A-Za-z0-9_-]{6,255}$/',$token)||!preg_match('/^\d{4}$/',$last4)||$month<1||$month>12||$year<(int)date('Y')) account_redirect('payment-methods/','Use a valid gateway token and safe card metadata.');
  $count=$conn->query('SELECT COUNT(*) c FROM payment_methods WHERE user_id='.(int)$uid)->fetch_assoc()['c'];$def=(!$count||isset($_POST['is_default']))?1:0;if($def){$s=$conn->prepare('UPDATE payment_methods SET is_default=0 WHERE user_id=?');$s->bind_param('i',$uid);$s->execute();}
  $s=$conn->prepare('INSERT INTO payment_methods(user_id,provider,payment_method_id,brand,last4,expiry_month,expiry_year,is_default) VALUES(?,?,?,?,?,?,?,?)');$s->bind_param('issssiii',$uid,$provider,$token,$brand,$last4,$month,$year,$def);$s->execute(); account_redirect('payment-methods/','Secure payment token saved.');
 }
 if ($action==='payment_delete'||$action==='payment_default') { $id=(int)($_POST['id']??0);if($action==='payment_delete'){$s=$conn->prepare('DELETE FROM payment_methods WHERE id=? AND user_id=?');$s->bind_param('ii',$id,$uid);$s->execute();}else{$conn->begin_transaction();$s=$conn->prepare('UPDATE payment_methods SET is_default=0 WHERE user_id=?');$s->bind_param('i',$uid);$s->execute();$s=$conn->prepare('UPDATE payment_methods SET is_default=1 WHERE id=? AND user_id=?');$s->bind_param('ii',$id,$uid);$s->execute();$conn->commit();}account_redirect('payment-methods/','Payment methods updated.'); }
 if ($action==='settings') { $lang=in_array($_POST['language']??'', ['en','th'],true)?$_POST['language']:'en';$currency=in_array($_POST['currency']??'',['THB','USD','EUR','GBP','JPY'],true)?$_POST['currency']:'THB';$ou=isset($_POST['order_updates'])?1:0;$pr=isset($_POST['promotions'])?1:0;$em=isset($_POST['email_notifications'])?1:0;$s=$conn->prepare('INSERT INTO user_settings(user_id,language,currency,order_updates,promotions,email_notifications) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE language=VALUES(language),currency=VALUES(currency),order_updates=VALUES(order_updates),promotions=VALUES(promotions),email_notifications=VALUES(email_notifications)');$s->bind_param('issiii',$uid,$lang,$currency,$ou,$pr,$em);$s->execute();account_redirect('settings/','Settings saved.'); }
 if ($action==='password') { $u=account_user($conn,$uid);if(empty($u['password'])||!password_verify($_POST['current_password']??'',$u['password'])||strlen($_POST['new_password']??'')<8) account_redirect('settings/','Current password is wrong or the new password is too short.');$hash=password_hash($_POST['new_password'],PASSWORD_DEFAULT);$s=$conn->prepare('UPDATE users SET password=? WHERE id=?');$s->bind_param('si',$hash,$uid);$s->execute();account_redirect('settings/','Password changed.'); }
}
$user=account_user($conn,$uid);$flash=$_SESSION['account_flash']??'';unset($_SESSION['account_flash']);$csrf=account_csrf();$editAddress=[];
if($accountPage==='addresses' && ($editId=(int)($_GET['edit']??0))){$es=$conn->prepare('SELECT * FROM addresses WHERE id=? AND user_id=?');$es->bind_param('ii',$editId,$uid);$es->execute();$editAddress=$es->get_result()->fetch_assoc()?:[];}
$base='../'; if($accountPage!=='profile')$base='../../';
function postButtons($action,$id,$label,$class='border'){global $csrf;$confirm=$action==='address_delete'?' onsubmit="return confirm(\'Remove this saved address?\')"':'';return '<form method="post"'.$confirm.'><input type="hidden" name="csrf" value="'.account_e($csrf).'"><input type="hidden" name="action" value="'.$action.'"><input type="hidden" name="id" value="'.$id.'"><button class="rounded '.$class.' px-3 py-2 text-sm">'.$label.'</button></form>';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Account | SPARK</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-gray-100 text-gray-900"><?php include __DIR__.'/../includes/site_header.php'; ?>
<main class="mx-auto max-w-6xl px-4 py-8"><div class="grid gap-6 md:grid-cols-[230px_1fr]"><aside class="rounded-xl bg-white p-5 shadow-sm"><h2 class="text-xl font-bold">My Account</h2><nav class="mt-4 flex gap-2 overflow-auto md:flex-col"><?php foreach([''=>'My Profile','orders/'=>'My Orders','addresses/'=>'Addresses','payment-methods/'=>'Payment Methods','settings/'=>'Settings'] as $path=>$label):?><a class="whitespace-nowrap rounded px-3 py-2 hover:bg-orange-50" href="<?php echo $base.'profile/'.$path;?>"><?php echo $label;?></a><?php endforeach;?><a class="rounded px-3 py-2 text-red-600" href="<?php echo $base;?>shopping/logout.php">Logout</a></nav></aside><section class="min-w-0 rounded-xl bg-white p-5 shadow-sm md:p-8"><?php if($flash):?><p class="mb-5 rounded bg-orange-50 p-3 text-orange-800"><?php echo account_e($flash);?></p><?php endif;?>
<?php if($accountPage==='profile'):?><h1 class="text-2xl font-bold">My Profile</h1><div class="mt-5 flex items-center gap-4"><div class="flex h-20 w-20 items-center justify-center rounded-full bg-orange-100 text-3xl font-bold text-orange-600"><?php echo account_e(strtoupper(substr($user['name'],0,1)));?></div><div><b class="text-xl"><?php echo account_e($user['name']);?></b><p class="text-gray-500"><?php echo account_e($user['email']);?></p></div></div><form method="post" class="mt-7 grid gap-4 sm:grid-cols-2"><input type="hidden" name="csrf" value="<?php echo $csrf;?>"><input type="hidden" name="action" value="profile"><?php foreach(['name'=>'Full name','email'=>'Email','phone'=>'Phone number'] as $n=>$l):?><label><span class="mb-1 block text-sm"><?php echo $l;?></span><input name="<?php echo $n;?>" value="<?php echo account_e($user[$n]??'');?>" class="w-full rounded border px-4 py-3" required></label><?php endforeach;?><label><span class="mb-1 block text-sm">Birthday (optional)</span><input type="date" name="birthday" value="<?php echo account_e($user['birthday']??'');?>" class="w-full rounded border px-4 py-3"></label><label><span class="mb-1 block text-sm">Gender (optional)</span><select name="gender" class="w-full rounded border px-4 py-3"><option value="">Prefer not to say</option><?php foreach(['female','male','nonbinary'] as $g):?><option <?php echo ($user['gender']??'')===$g?'selected':'';?> value="<?php echo $g;?>"><?php echo ucfirst($g);?></option><?php endforeach;?></select></label><button class="rounded bg-orange-500 px-6 py-3 font-bold text-white sm:col-span-2">Save Profile</button></form>
<?php elseif($accountPage==='addresses'):$res=$conn->query('SELECT * FROM addresses WHERE user_id='.(int)$uid.' ORDER BY is_default DESC,id DESC');?><h1 class="text-2xl font-bold">Shipping Addresses</h1><div class="mt-5 grid gap-4"><?php while($a=$res->fetch_assoc()):?><article class="rounded border p-4"><div class="flex justify-between"><b><?php echo account_e($a['label']);?></b><?php if($a['is_default']):?><span class="text-sm font-bold text-orange-600">Default</span><?php endif;?></div><p class="mt-2 text-sm leading-6"><?php echo account_e($a['full_name']);?> · <?php echo account_e($a['phone']);?><br><?php echo account_e($a['address_line']);?><br><?php echo account_e(trim($a['subdistrict'].' '.$a['district'].' '.$a['province'].' '.$a['postal_code']));?>, <?php echo account_e($a['country']);?></p><div class="mt-3 flex gap-2"><a href="?edit=<?php echo (int)$a['id'];?>" class="rounded border px-3 py-2 text-sm">Edit</a><?php if(!$a['is_default'])echo postButtons('address_default',$a['id'],'Set Default');echo postButtons('address_delete',$a['id'],'Delete','border border-red-300 text-red-600');?></div></article><?php endwhile;?></div><h2 class="mt-8 text-xl font-bold"><?php echo $editAddress?'Edit':'Add';?> Address</h2><form method="post" class="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="csrf" value="<?php echo $csrf;?>"><input type="hidden" name="action" value="address_save"><input type="hidden" name="id" value="<?php echo (int)($editAddress['id']??0);?>"><?php foreach(['label'=>'Label','full_name'=>'Full name','phone'=>'Phone','address_line'=>'Address line','subdistrict'=>'Subdistrict','district'=>'District','province'=>'Province','postal_code'=>'Postal code','country'=>'Country'] as $n=>$l):?><label class="<?php echo $n==='address_line'?'sm:col-span-2':'';?>"><span class="text-sm"><?php echo $l;?></span><input name="<?php echo $n;?>" value="<?php echo account_e($editAddress[$n]??($n==='country'?'Thailand':''));?>" class="mt-1 w-full rounded border px-3 py-2" <?php echo $n==='subdistrict'?'':'required';?>></label><?php endforeach;?><label class="flex items-center gap-2"><input type="checkbox" name="is_default" <?php echo !empty($editAddress['is_default'])?'checked':'';?>> Set as default</label><button class="rounded bg-orange-500 p-3 font-bold text-white sm:col-span-2">Save Address</button></form>
<?php elseif($accountPage==='payments'):$res=$conn->query('SELECT * FROM payment_methods WHERE user_id='.(int)$uid.' ORDER BY is_default DESC,id DESC');?><h1 class="text-2xl font-bold">Payment Methods</h1><p class="mt-2 text-sm text-gray-500">Only secure gateway tokens and masked metadata are stored. Full card numbers and CVV are never accepted.</p><div class="mt-5 grid gap-4"><?php while($p=$res->fetch_assoc()):?><article class="rounded border p-4"><b><?php echo account_e($p['brand']);?> •••• <?php echo account_e($p['last4']);?></b><p class="text-sm text-gray-500">Expires <?php echo sprintf('%02d/%02d',$p['expiry_month'],$p['expiry_year']%100);?> · <?php echo account_e(strtoupper($p['provider']));?></p><?php if($p['is_default']):?><span class="text-sm font-bold text-orange-600">Default</span><?php endif;?><div class="mt-3 flex gap-2"><?php if(!$p['is_default'])echo postButtons('payment_default',$p['id'],'Set Default');echo postButtons('payment_delete',$p['id'],'Remove','border border-red-300 text-red-600');?></div></article><?php endwhile;?></div><details class="mt-8"><summary class="cursor-pointer font-bold">Add gateway-tokenized card</summary><form method="post" class="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="csrf" value="<?php echo $csrf;?>"><input type="hidden" name="action" value="payment_save"><?php foreach(['provider'=>'Provider (stripe/opn/omise/2c2p)','payment_method_id'=>'Gateway payment method ID','brand'=>'Brand','last4'=>'Last 4 digits','expiry_month'=>'Expiry month','expiry_year'=>'Expiry year'] as $n=>$l):?><label><span class="text-sm"><?php echo $l;?></span><input name="<?php echo $n;?>" class="mt-1 w-full rounded border px-3 py-2" required></label><?php endforeach;?><label><input type="checkbox" name="is_default"> Set as default</label><button class="rounded bg-orange-500 p-3 font-bold text-white sm:col-span-2">Save Token</button></form></details>
<?php elseif($accountPage==='settings'):$s=$conn->query('SELECT * FROM user_settings WHERE user_id='.(int)$uid)->fetch_assoc()?:['language'=>'en','currency'=>'THB','order_updates'=>1,'promotions'=>0,'email_notifications'=>1];?><h1 class="text-2xl font-bold">Settings</h1><form method="post" class="mt-5 space-y-4"><input type="hidden" name="csrf" value="<?php echo $csrf;?>"><input type="hidden" name="action" value="settings"><label class="block">Language <select name="language" class="mt-1 w-full rounded border p-3"><option value="en">English</option><option value="th" <?php echo $s['language']==='th'?'selected':'';?>>Thai</option></select></label><label class="block">Currency <select name="currency" class="mt-1 w-full rounded border p-3"><?php foreach(['THB','USD','EUR','GBP','JPY'] as $c):?><option <?php echo $s['currency']===$c?'selected':'';?>><?php echo $c;?></option><?php endforeach;?></select></label><?php foreach(['order_updates'=>'Order updates','promotions'=>'Promotions','email_notifications'=>'Email notifications'] as $n=>$l):?><label class="block"><input type="checkbox" name="<?php echo $n;?>" <?php echo $s[$n]?'checked':'';?>> <?php echo $l;?></label><?php endforeach;?><button class="rounded bg-orange-500 px-6 py-3 font-bold text-white">Save Settings</button></form><h2 class="mt-9 text-xl font-bold">Change Password</h2><form method="post" class="mt-4 grid gap-3"><input type="hidden" name="csrf" value="<?php echo $csrf;?>"><input type="hidden" name="action" value="password"><input type="password" name="current_password" placeholder="Current password" class="rounded border p-3" required><input type="password" name="new_password" minlength="8" placeholder="New password (8+ characters)" class="rounded border p-3" required><button class="rounded border p-3 font-bold">Change Password</button></form>
<?php else:$q=$conn->prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC');$q->bind_param('i',$uid);$q->execute();$res=$q->get_result();?><h1 class="text-2xl font-bold">My Orders</h1><div class="mt-5 divide-y rounded border"><?php while($o=$res->fetch_assoc()):?><div class="flex justify-between p-4"><div><b><?php echo account_e($o['order_number']?:('#'.$o['id']));?></b><p class="text-sm text-gray-500"><?php echo account_e($o['created_at']);?> · <?php echo account_e($o['status']);?></p></div><b>$<?php echo number_format($o['total'],2);?></b></div><?php endwhile;?></div><?php endif;?></section></div></main></body></html>
