ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS order_number VARCHAR(30) NULL UNIQUE,
    ADD COLUMN IF NOT EXISTS shipping_json TEXT NULL,
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(40) NULL,
    ADD COLUMN IF NOT EXISTS payment_status VARCHAR(40) NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS shipping_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS discount DECIMAL(10,2) NOT NULL DEFAULT 0.00;

ALTER TABLE order_items
    ADD COLUMN IF NOT EXISTS product_name VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS product_image VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS size VARCHAR(20) NULL;
