<?php session_start();
if (empty($_SESSION['user_id'])) { header('Location: ../index.php?login=1&redirect=' . rawurlencode($_SERVER['REQUEST_URI'] ?? '/shop/shopping/payment.php')); exit; }
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payment | SPARK</title><script src="https://cdn.tailwindcss.com"></script>
<style>.method-card:has(input:checked){border-color:#f97316;background:#fff7ed}.qr-placeholder{background:repeating-conic-gradient(#111 0 25%,#fff 0 50%) 50%/18px 18px}</style></head>
<body class="bg-gray-100 text-gray-900">
<header class="bg-white shadow"><div class="flex items-center justify-between px-5 py-4 md:px-10"><a href="../index.php" class="text-3xl font-bold">SPARK</a><span class="text-sm text-gray-500">Secure checkout</span></div></header>
<nav class="overflow-x-auto border-t bg-white"><div class="min-w-[720px]"><?php include __DIR__ . '/../includes/navbar.php'; ?></div></nav>
<main class="mx-auto max-w-7xl px-4 py-8">
<div class="mb-8 flex items-center justify-center text-center text-xs md:text-sm"><a href="cart.php" class="text-gray-500"><b class="mx-auto block h-8 w-8 rounded-full border leading-7">1</b>Shopping Cart</a><i class="mx-3 h-px max-w-48 flex-1 bg-gray-300"></i><a href="checkout.php" class="text-gray-500"><b class="mx-auto block h-8 w-8 rounded-full border leading-7">2</b>Shipping</a><i class="mx-3 h-px max-w-48 flex-1 bg-gray-300"></i><div class="text-orange-600"><b class="mx-auto block h-8 w-8 rounded-full bg-orange-500 leading-8 text-white">3</b><strong>Payment</strong></div></div>
<div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_390px]">
<section class="rounded bg-white p-5 shadow-sm md:p-7"><h1 class="text-2xl font-bold">Payment method</h1><p class="mt-2 text-sm text-gray-500">Choose one payment option. Online methods remain pending until confirmed by a real gateway.</p>
<div class="mt-6 grid gap-3 sm:grid-cols-2">
<div id="savedPaymentMethods" class="contents"></div>
<label class="method-card cursor-pointer rounded border-2 p-4"><input type="radio" name="payment_method" value="card" class="mr-2 accent-orange-500"><strong>Credit / Debit Card</strong><p class="mt-1 text-xs text-gray-500">Gateway integration required</p></label>
<label class="method-card cursor-pointer rounded border-2 p-4"><input type="radio" name="payment_method" value="promptpay" class="mr-2 accent-orange-500"><strong>PromptPay QR</strong><p class="mt-1 text-xs text-gray-500">QR placeholder only</p></label>
<label class="method-card cursor-pointer rounded border-2 p-4"><input type="radio" name="payment_method" value="bank_transfer" class="mr-2 accent-orange-500"><strong>Bank Transfer</strong><p class="mt-1 text-xs text-gray-500">Requires slip verification</p></label>
<label class="method-card cursor-pointer rounded border-2 p-4"><input type="radio" name="payment_method" value="cod" class="mr-2 accent-orange-500"><strong>Cash on Delivery</strong><p class="mt-1 text-xs text-gray-500">Pay upon delivery</p></label>
</div>

<div id="methodPanels" class="mt-6">
<div data-panel="card" class="hidden rounded border p-5"><h2 class="font-bold">Card details</h2><p class="mt-1 text-xs text-amber-700">UI validation only. Card information is never stored or sent to SPARK.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2"><span class="mb-1 block text-sm">Cardholder Name</span><input id="cardName" autocomplete="cc-name" class="w-full rounded border px-4 py-3"></label><label class="sm:col-span-2"><span class="mb-1 block text-sm">Card Number</span><input id="cardNumber" inputmode="numeric" autocomplete="cc-number" maxlength="19" placeholder="1234 5678 9012 3456" class="w-full rounded border px-4 py-3"></label><label><span class="mb-1 block text-sm">Expiry Date</span><input id="cardExpiry" inputmode="numeric" autocomplete="cc-exp" maxlength="5" placeholder="MM/YY" class="w-full rounded border px-4 py-3"></label><label><span class="mb-1 block text-sm">CVV</span><input id="cardCvv" type="password" inputmode="numeric" autocomplete="cc-csc" maxlength="4" class="w-full rounded border px-4 py-3"></label></div></div>
<div data-panel="promptpay" class="hidden rounded border p-5 text-center"><h2 class="font-bold">PromptPay QR</h2><div class="qr-placeholder mx-auto mt-4 h-44 w-44 border-8 border-white outline outline-1 outline-gray-300" aria-label="QR placeholder"></div><p class="mt-4 font-semibold">Scan QR code to complete payment</p><p class="mt-2 text-xl font-bold text-orange-600">$<span class="panelTotal">0.00</span></p><p class="mt-2 text-xs text-amber-700">Placeholder only — no payable PromptPay QR has been generated.</p></div>
<div data-panel="bank_transfer" class="hidden rounded border p-5"><h2 class="font-bold">Bank Transfer</h2><div class="mt-4 space-y-2 text-sm"><p><b>Bank:</b> Demo Bank (not payable)</p><p><b>Account name:</b> SPARK Demo Merchant</p><p><b>Account number:</b> Configure merchant account</p><p><b>Amount:</b> $<span class="panelTotal font-bold text-orange-600">0.00</span></p></div><label class="mt-5 block"><span class="mb-2 block text-sm font-medium">Upload payment slip</span><input id="slip" type="file" accept="image/*,.pdf" class="block w-full rounded border p-3 text-sm"><span id="slipName" class="mt-2 block text-xs text-gray-500">Frontend preview only; the file is not uploaded yet.</span></label></div>
<div data-panel="cod" class="hidden rounded border p-5"><h2 class="font-bold">Cash on Delivery</h2><p class="mt-2 text-gray-600">Pay when your order is delivered.</p></div>
</div>
<p id="paymentError" class="mt-4 hidden rounded bg-red-50 p-3 text-sm text-red-700"></p>
<div class="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><a href="checkout.php" class="rounded border px-6 py-3 text-center hover:border-orange-500">← Back to Shipping</a><button id="placeOrder" class="rounded bg-orange-500 px-8 py-3 font-bold text-white hover:bg-orange-600 disabled:cursor-not-allowed disabled:opacity-60">Place Order</button></div>
</section>

<aside class="h-fit rounded bg-white p-5 shadow-sm lg:sticky lg:top-5"><h2 class="text-xl font-bold">Order Summary</h2><div id="summaryItems" class="mt-5 max-h-[420px] space-y-4 overflow-auto"></div><dl class="mt-5 space-y-3 border-t pt-5 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd>$<span id="subtotal">0.00</span></dd></div><div class="flex justify-between"><dt>Shipping fee</dt><dd>$0.00</dd></div><div class="flex justify-between"><dt>Discount</dt><dd class="text-green-600">− $0.00</dd></div><div class="flex justify-between border-t pt-4 text-xl"><dt>Total</dt><dd class="font-bold text-orange-600">$<span id="finalTotal">0.00</span></dd></div></dl><div id="shippingPreview" class="mt-5 border-t pt-5 text-sm"></div></aside>
</div></main>
<script>
const CART_KEY='cart', SHIPPING_KEY='shippingInfo';
const money=n=>Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
let cart=[],shipping={};try{cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]');shipping=JSON.parse(localStorage.getItem(SHIPPING_KEY)||'{}')}catch(error){}
fetch('account_data.php').then(r=>r.json()).then(data=>{if(!data.payment_methods?.length)return;document.querySelector('#savedPaymentMethods').innerHTML=data.payment_methods.map((p,i)=>`<label class="method-card cursor-pointer rounded border-2 p-4"><input type="radio" name="payment_method" value="saved:${p.id}" ${i===0?'checked':''} class="mr-2 accent-orange-500"><strong>${escapeHtml(p.brand)} •••• ${escapeHtml(p.last4)}</strong><p class="mt-1 text-xs text-gray-500">Expires ${String(p.expiry_month).padStart(2,'0')}/${String(p.expiry_year).slice(-2)}${p.is_default==1?' · Default':''}</p></label>`).join('');document.querySelectorAll('[name="payment_method"]').forEach(radio=>radio.addEventListener('change',()=>{document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('hidden',panel.dataset.panel!==radio.value));hideError()}))});
const shippingFields=['name','email','phone','address','city','province','postal_code'];
if(!Array.isArray(cart)||!cart.length)location.href='cart.php';else if(shippingFields.some(field=>!String(shipping[field]||'').trim()))location.href='checkout.php';
const total=cart.reduce((sum,item)=>sum+Number(item.price)*Math.max(1,Number(item.quantity)||1),0);
document.querySelector('#summaryItems').innerHTML=cart.map(item=>`<div class="flex gap-3"><img src="../assets/images/${escapeHtml(item.image)}" class="h-16 w-16 rounded object-contain"><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">${escapeHtml(item.name)}</p><p class="text-xs text-gray-500">Size ${escapeHtml(item.size)} · Qty ${Math.max(1,Number(item.quantity)||1)}</p></div><b class="text-sm">$${money(Number(item.price)*Math.max(1,Number(item.quantity)||1))}</b></div>`).join('');
document.querySelector('#subtotal').textContent=money(total);document.querySelector('#finalTotal').textContent=money(total);document.querySelectorAll('.panelTotal').forEach(el=>el.textContent=money(total));
document.querySelector('#shippingPreview').innerHTML=`<h3 class="font-bold">Shipping to</h3><p class="mt-2">${escapeHtml(shipping.name)}</p><p class="text-gray-500">${escapeHtml(shipping.address)}, ${escapeHtml(shipping.city)}, ${escapeHtml(shipping.province)} ${escapeHtml(shipping.postal_code)}</p>`;
document.querySelectorAll('[name="payment_method"]').forEach(radio=>radio.addEventListener('change',()=>{document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('hidden',panel.dataset.panel!==radio.value));hideError()}));
document.querySelector('#cardNumber').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,16).replace(/(.{4})/g,'$1 ').trim());
document.querySelector('#cardExpiry').addEventListener('input',e=>{let value=e.target.value.replace(/\D/g,'').slice(0,4);if(value.length>2)value=value.slice(0,2)+'/'+value.slice(2);e.target.value=value});
document.querySelector('#cardCvv').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4));
document.querySelector('#slip').addEventListener('change',e=>document.querySelector('#slipName').textContent=e.target.files[0]?`Selected: ${e.target.files[0].name} (not uploaded yet)`:'Frontend preview only; the file is not uploaded yet.');
function showError(message){const box=document.querySelector('#paymentError');box.textContent=message;box.classList.remove('hidden')}
function hideError(){document.querySelector('#paymentError').classList.add('hidden')}
function luhn(number){let sum=0,double=false;for(let i=number.length-1;i>=0;i--){let digit=+number[i];if(double&&(digit*=2)>9)digit-=9;sum+=digit;double=!double}return sum%10===0}
function validCard(){const name=document.querySelector('#cardName').value.trim(),number=document.querySelector('#cardNumber').value.replace(/\D/g,''),expiry=document.querySelector('#cardExpiry').value,cvv=document.querySelector('#cardCvv').value;if(name.length<2||number.length<13||!luhn(number)||!/^(0[1-9]|1[0-2])\/\d{2}$/.test(expiry)||!/^\d{3,4}$/.test(cvv))return false;const [month,year]=expiry.split('/').map(Number),now=new Date(),expiryEnd=new Date(2000+year,month,0,23,59,59);return expiryEnd>=now}
document.querySelector('#placeOrder').addEventListener('click',async()=>{hideError();const method=document.querySelector('[name="payment_method"]:checked')?.value;if(!method){showError('Please select a payment method.');return}if(method==='card'&&!validCard()){showError('Please enter valid card details. No card data will be stored.');return}const button=document.querySelector('#placeOrder');button.disabled=true;button.textContent='Creating Order…';const orderedKeys=new Set(cart.map(item=>`${Number(item.id)}:${item.size}`));try{const response=await fetch('create_order.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart.map(({id,size,quantity})=>({id,size,quantity})),shipping,payment_method:method})});const result=await response.json();if(response.status===401||result.login_required){alert('Please login to continue shopping.');location.href='../index.php?login=1&redirect='+encodeURIComponent(window.location.pathname+window.location.search);return}if(!result.ok)throw new Error(result.message||'Could not create order.');const current=JSON.parse(localStorage.getItem(CART_KEY)||'[]');localStorage.setItem(CART_KEY,JSON.stringify(current.filter(item=>!orderedKeys.has(`${Number(item.id)}:${item.size}`))));localStorage.removeItem(SHIPPING_KEY);location.href=`order_success.php?order=${encodeURIComponent(result.order_number)}`}catch(error){showError(error.message);button.disabled=false;button.textContent='Place Order'}});
</script></body></html>
