<?php
require_once __DIR__.'/../includes/account.php';
if(!account_user_id()){header('Location: ../index.php?login=1&redirect='.rawurlencode($_SERVER['REQUEST_URI']));exit;}
require_once __DIR__.'/../includes/stripe.php';require_once __DIR__.'/../includes/payment_ui.php';
$config=spark_payment_config();$enabled=(bool)($config['secret_key']&&$config['publishable_key']);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Checkout | SPARK</title><link rel="stylesheet" href="../assets/payment.css"></head>
<body class="payment-page"><main class="checkout-shell"><?php payment_steps();?><h1>Checkout</h1><p class="pay-subtitle">Complete your payment to place your order.</p>
<div class="checkout-columns"><section><div class="pay-box shipping-card"><div class="pay-row"><h2>Shipping Address</h2><a class="pay-link" href="checkout.php">Change</a></div><div id="shippingPreview" class="address-content">Loading your address…</div></div>
<h2 class="payment-title">Payment Method</h2>
<div class="payment-option"><label class="payment-choice"><input type="radio" name="payment_method" value="card" checked><span><strong>Credit / Debit Card</strong><small>Pay securely with your card</small></span><?php echo payment_brands();?></label>
<div class="payment-fields"><div id="savedCardChoice" hidden><label class="pay-label" for="savedCard">Choose a card</label><select id="savedCard" class="pay-input"><option value="">Use a new card</option></select></div><label class="pay-label">Card information</label><div id="cardElement"><?php echo payment_placeholder();?></div><?php if(!$enabled):?><p class="pay-unavailable">Card payments are currently unavailable. Please choose cash on delivery.</p><?php endif;?>
<label class="pay-label" for="cardholder">Cardholder name</label><input id="cardholder" class="pay-input" placeholder="Name on card" autocomplete="cc-name" <?php echo !$enabled?'disabled':'';?>><label class="pay-check"><input type="checkbox" id="saveCard" checked>Save this card for future orders</label></div></div>
<div class="payment-option disabled"><label class="payment-choice"><input type="radio" name="payment_method" disabled><span><strong>QR Code / Bank Payment</strong><small>Currently unavailable</small></span><span class="method-logo promptpay">PromptPay</span></label></div>
<div class="payment-option disabled"><label class="payment-choice"><input type="radio" name="payment_method" disabled><span><strong>TrueMoney Wallet</strong><small>Currently unavailable</small></span><span class="method-logo truemoney">▰ truemoney</span></label></div>
<div class="payment-option"><label class="payment-choice"><input type="radio" name="payment_method" value="cod"><span><strong>Other payment methods</strong><small>Cash on delivery</small></span><span style="margin-left:auto;font-size:24px">›</span></label><div class="payment-fields"><p class="pay-note" style="margin-bottom:15px">Pay when your order is delivered.</p></div></div>
<div id="paymentError" class="pay-error" role="alert"></div><button id="cancelPayment" type="button" class="pay-link" hidden>Cancel pending payment and start again</button></section>
<aside><section class="pay-box order-summary"><div class="pay-row"><h2>Order Summary</h2><a href="cart.php" class="pay-link">Edit</a></div><div id="summaryItems" class="summary-items" aria-live="polite">Loading your cart…</div><div class="summary-totals"><div><span>Subtotal</span><span id="subtotal">—</span></div><div><span>Shipping</span><span id="shippingTotal">—</span></div><div><span>Discount</span><span id="discountTotal">—</span></div><div class="total"><span>Total</span><span id="finalTotal">—</span></div></div><button id="placeOrder" class="pay-gold pay-wide" disabled><?php echo payment_icon('lock');?> <span id="payLabel">Pay</span></button><p class="summary-terms">By placing your order, you confirm your shipping details and selected payment method.</p></section>
<section class="trust-panel" aria-label="Shopping assurances"><div class="trust-item"><span class="trust-icon"><?php echo payment_icon('lock');?></span><div><strong>Secure Payment</strong><p>Your payment information is encrypted.</p></div></div><div class="trust-item"><span class="trust-icon"><?php echo payment_icon('bolt');?></span><div><strong>Fast &amp; Reliable</strong><p>Order updates, every step of the way.</p></div></div><div class="trust-item"><span class="trust-icon"><?php echo payment_icon('returns');?></span><div><strong>Here to Help</strong><p>Manage your orders from My Account.</p></div></div></section></aside></div><div class="checkout-footer"><a href="checkout.php">← Back to shipping</a></div></main>
<script>window.sparkPayment=<?php echo json_encode(['key'=>$enabled?$config['publishable_key']:'','csrf'=>account_csrf(),'currency'=>$config['currency']],JSON_HEX_TAG|JSON_HEX_AMP);?>;</script><?php if($enabled):?><script src="https://js.stripe.com/v3/"></script><?php endif;?><script src="../assets/checkout-payment.js"></script></body></html>
