<?php
if (!isset($collectionType,$heroTitle,$heroSubtitle,$heroDescription,$categoryOptions)) die('Collection configuration missing.');
require_once __DIR__.'/../config/connection.php';
function spark_e($v): string { return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); }
$columns=[]; foreach(mysqli_query($conn,'SHOW COLUMNS FROM products') as $c) $columns[$c['Field']]=true;
$saleSql=isset($columns['sale_price'])?'p.sale_price':'IF(p.on_sale=1,ROUND(p.price*.8,2),NULL)';
$discountSql=isset($columns['discount'])?'p.discount':'IF(p.on_sale=1,20,0)';
$where=$collectionType==='sale'?'p.on_sale=1':'p.audience=?';
$stmt=mysqli_prepare($conn,"SELECT p.*,c.name category_name,$saleSql sale_price_display,$discountSql discount_display FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE $where ORDER BY p.id");
if($collectionType!=='sale') mysqli_stmt_bind_param($stmt,'s',$collectionType);
mysqli_stmt_execute($stmt); $result=mysqli_stmt_get_result($stmt); $products=[];
while($row=mysqli_fetch_assoc($result)) $products[]=$row;
$brands=array_values(array_unique(array_filter(array_column($products,'brand')))); sort($brands); $searchCategory=$collectionType;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo spark_e($heroTitle); ?> | SPARK</title><script src="https://cdn.tailwindcss.com"></script>
<style>.product-card[hidden]{display:none}@media(max-width:767px){#filters{display:none}#filters.filter-open{display:block}}</style></head><body class="bg-gray-100 text-gray-900">
<?php include __DIR__.'/site_header.php'; ?>
<main><section class="relative overflow-hidden bg-zinc-950 px-5 py-16 text-white md:px-10 md:py-24"><div class="absolute -right-20 -top-28 h-80 w-80 rounded-full bg-orange-500/30 blur-3xl"></div><div class="relative mx-auto max-w-7xl"><p class="mb-3 text-sm font-bold tracking-[.3em] text-orange-400">SPARK / COLLECTION</p><h1 class="text-4xl font-black tracking-tight md:text-6xl"><?php echo spark_e($heroTitle); ?></h1><h2 class="mt-4 text-xl font-semibold md:text-2xl"><?php echo spark_e($heroSubtitle); ?></h2><p class="mt-2 max-w-xl text-zinc-300"><?php echo spark_e($heroDescription); ?></p></div></section>
<section class="mx-auto max-w-7xl px-4 py-8 md:px-6"><div class="mb-6 flex gap-2 overflow-x-auto pb-2" id="categories">
<?php foreach($categoryOptions as $i=>$category): ?><button data-category="<?php echo spark_e(strtolower($category)); ?>" class="category-btn shrink-0 rounded-full border px-5 py-2 text-sm font-semibold <?php echo $i===0?'border-orange-500 bg-orange-500 text-white':'bg-white'; ?>"><?php echo spark_e($category); ?></button><?php endforeach; ?>
</div><div class="mb-5 flex items-center justify-between"><div><strong id="resultCount"><?php echo count($products); ?></strong> products</div><div class="flex gap-2"><button id="filterToggle" class="rounded border bg-white px-4 py-2 md:hidden">Filters</button><select id="sort" class="max-w-44 rounded border bg-white px-3 py-2"><option value="featured">Sort by: Featured</option><option value="newest">Newest</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="rating">Top Rated</option></select></div></div>
<div class="grid gap-6 md:grid-cols-[220px_minmax(0,1fr)]"><aside id="filters" class="h-fit rounded-xl bg-white p-5 shadow-sm md:block"><div class="mb-5 flex justify-between"><h2 class="font-bold">Filters</h2><button id="clear" class="text-xs text-orange-600">Clear all</button></div><label class="mb-5 block text-sm font-semibold">Brand<select id="brand" class="mt-2 w-full rounded border p-2 font-normal"><option value="">All brands</option><?php foreach($brands as $brand): ?><option><?php echo spark_e($brand); ?></option><?php endforeach; ?></select></label><label class="mb-5 block text-sm font-semibold">Max price <span id="priceLabel" class="float-right text-orange-600">$5,000</span><input id="price" type="range" min="500" max="5000" step="100" value="5000" class="mt-3 w-full accent-orange-500"></label><label class="mb-5 block text-sm font-semibold">Size<select id="size" class="mt-2 w-full rounded border p-2 font-normal"><option value="">Any size</option><option>S</option><option>M</option><option>L</option></select></label><label class="block text-sm font-semibold">Minimum rating<select id="rating" class="mt-2 w-full rounded border p-2 font-normal"><option value="0">Any rating</option><option value="4">4★ & up</option><option value="4.5">4.5★ & up</option><option value="4.8">4.8★ & up</option></select></label></aside>
<div><div id="grid" class="grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-3 xl:grid-cols-4">
<?php foreach($products as $p): $effective=$p['sale_price_display']?:$p['price']; $isSale=(int)$p['on_sale']===1; ?>
<a class="product-card group flex min-w-0 flex-col overflow-hidden rounded-xl bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg" href="product_detail.php?id=<?php echo (int)$p['id']; ?>" data-name="<?php echo spark_e(strtolower($p['name'].' '.$p['description'])); ?>" data-brand="<?php echo spark_e($p['brand']); ?>" data-price="<?php echo (float)$effective; ?>" data-rating="<?php echo (float)$p['rating']; ?>" data-sizes="<?php echo spark_e($p['sizes']); ?>" data-created="<?php echo strtotime($p['created_at']); ?>" data-sold="<?php echo (int)$p['sold_count']; ?>" data-sale="<?php echo $isSale?'1':'0'; ?>"><div class="relative aspect-square bg-zinc-50 p-3"><img class="h-full w-full object-contain transition group-hover:scale-105" src="../assets/images/<?php echo spark_e($p['image']); ?>" alt="<?php echo spark_e($p['name']); ?>"><?php if($isSale): ?><span class="absolute left-2 top-2 rounded bg-red-600 px-2 py-1 text-xs font-bold text-white">-<?php echo (int)$p['discount_display']; ?>%</span><?php endif; ?></div><div class="flex flex-1 flex-col p-3 sm:p-4"><p class="text-xs font-bold uppercase text-gray-400"><?php echo spark_e($p['brand']); ?></p><h3 class="mt-1 line-clamp-2 text-sm font-semibold sm:text-base"><?php echo spark_e($p['name']); ?></h3><div class="mt-2 text-xs text-yellow-500">★★★★★ <span class="text-gray-500"><?php echo number_format((float)$p['rating'],1); ?></span></div><div class="mt-auto pt-3"><?php if($isSale): ?><p class="text-xs text-gray-400 line-through">Original: $<?php echo number_format((float)$p['price'],2); ?></p><p class="font-black text-red-600">$<?php echo number_format((float)$effective,2); ?></p><?php else: ?><p class="font-bold text-green-600">$<?php echo number_format((float)$p['price'],2); ?></p><?php endif; ?></div></div></a>
<?php endforeach; ?></div><div id="empty" class="hidden rounded-xl bg-white py-20 text-center"><div class="text-4xl">👟</div><h2 class="mt-3 text-xl font-bold">No products match</h2><p class="mt-1 text-gray-500">Try clearing one or more filters.</p></div><div id="pagination" class="mt-8 flex justify-center gap-2"></div></div></div></section></main>
<?php include __DIR__.'/footer.php'; ?>
<script src="../assets/collection.js"></script></body></html>
