<section id="productInformation" class="mx-auto mt-16 max-w-7xl px-4 md:px-10">
<div class="flex overflow-x-auto border-b bg-white" role="tablist">
<button class="product-tab shrink-0 border-b-2 border-orange-500 px-5 py-4 font-semibold text-orange-600" data-tab="description">Description</button>
<button class="product-tab shrink-0 border-b-2 border-transparent px-5 py-4 font-semibold" data-tab="reviews">Reviews (<span id="tabReviewCount"><?php echo $reviewCount; ?></span>)</button>
<button class="product-tab shrink-0 border-b-2 border-transparent px-5 py-4 font-semibold" data-tab="shipping">Shipping &amp; Returns</button>
</div>
<div id="tab-description" class="tab-panel rounded-b bg-white p-6 md:p-8"><h2 class="mb-4 text-2xl font-bold">Product Description</h2><p class="leading-relaxed text-gray-600"><?php echo htmlspecialchars($row['description']); ?></p></div>
<div id="tab-shipping" class="tab-panel hidden rounded-b bg-white p-6 md:p-8"><h2 class="mb-4 text-2xl font-bold">Shipping &amp; Returns</h2><div class="space-y-3 text-gray-600"><p><strong class="text-gray-900">Delivery:</strong> Shipping options and fees are calculated during checkout.</p><p><strong class="text-gray-900">Returns:</strong> Unworn products may be returned in their original packaging within 7 days of delivery.</p></div></div>
<div id="tab-reviews" class="tab-panel hidden rounded-b bg-white p-4 md:p-8">
<div class="flex flex-col gap-8 border-b pb-8 lg:flex-row lg:items-center">
<div class="lg:w-52"><h2 class="text-2xl font-bold">Customer Reviews</h2><div id="summaryAverage" class="mt-3 text-5xl font-black"><?php echo number_format($averageRating,1); ?></div><div id="summaryStars" class="text-xl text-yellow-400"><?php echo str_repeat('★',(int)round($averageRating)).str_repeat('☆',5-(int)round($averageRating)); ?></div><p class="mt-1 text-sm text-gray-500">Based on <span id="summaryCount"><?php echo $reviewCount; ?></span> reviews</p></div>
<div id="ratingDistribution" class="min-w-0 flex-1 space-y-2"></div>
<div class="lg:w-52 lg:text-right"><button id="writeReview" class="w-full rounded bg-orange-500 px-6 py-3 font-semibold text-white hover:bg-orange-600 lg:w-auto">Write a Review</button><p id="loginReviewNote" class="mt-2 hidden text-sm text-red-600">Please login to write a review.</p></div>
</div>
<div class="mt-7 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div id="ratingFilters" class="flex gap-2 overflow-x-auto pb-1"><button data-rating="0" class="review-filter shrink-0 rounded-full bg-orange-500 px-4 py-2 text-sm text-white">All</button><?php for($star=5;$star>=1;$star--): ?><button data-rating="<?php echo $star; ?>" class="review-filter shrink-0 rounded-full border px-4 py-2 text-sm"><?php echo $star; ?> Stars</button><?php endfor; ?></div><select id="reviewSort" class="rounded border px-3 py-2"><option value="recent">Most Recent</option><option value="highest">Highest Rating</option><option value="lowest">Lowest Rating</option><option value="helpful">Most Helpful</option></select></div>
<div id="reviewList" class="mt-3 divide-y"></div><div id="reviewPagination" class="mt-7 flex flex-wrap justify-center gap-2"></div>
</div></section>

<div id="reviewModal" class="fixed inset-0 z-50 hidden items-center justify-center overflow-y-auto bg-black/50 p-4"><div class="relative my-8 w-full max-w-xl rounded-xl bg-white p-6 shadow-xl"><button id="closeReview" class="absolute right-4 top-3 text-2xl">×</button><h2 class="text-2xl font-bold">Write a Review</h2><form id="reviewForm" class="mt-5" enctype="multipart/form-data"><input type="hidden" name="product_id" value="<?php echo $id; ?>"><input type="hidden" name="action" value="create"><input type="hidden" name="rating" id="reviewRating" value="0"><label class="font-semibold">Your Rating</label><div id="starPicker" class="my-2 flex w-fit gap-1 text-4xl text-gray-300" aria-label="Choose rating"><?php for($star=1;$star<=5;$star++): ?><button type="button" data-star="<?php echo $star; ?>" class="review-star min-h-11 min-w-11" aria-label="<?php echo $star; ?> stars">★</button><?php endfor; ?></div><label class="mt-4 block font-semibold">Review title <span class="font-normal text-gray-400">(optional)</span><input name="title" maxlength="160" class="mt-2 w-full rounded border px-4 py-3"></label><label class="mt-4 block font-semibold">Review<textarea name="comment" maxlength="5000" rows="5" required class="mt-2 w-full rounded border px-4 py-3" placeholder="Write your review here..."></textarea></label><label class="mt-4 block font-semibold">Upload Photos <span class="font-normal text-gray-400">(optional, up to 3)</span><input name="images[]" type="file" multiple accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full rounded border p-3 text-sm"></label><p id="reviewFormMessage" class="mt-4 hidden text-sm"></p><div class="mt-6 flex justify-end gap-3"><button type="button" id="cancelReview" class="rounded border px-5 py-3">Cancel</button><button id="submitReview" class="rounded bg-orange-500 px-5 py-3 font-semibold text-white">Submit Review</button></div></form></div></div>
<div id="reviewImageModal" class="fixed inset-0 z-[60] hidden items-center justify-center bg-black/80 p-4"><button id="closeImagePreview" class="absolute right-6 top-4 text-4xl text-white">×</button><img id="reviewImageLarge" class="max-h-[90vh] max-w-full rounded object-contain"></div>
